color.ini
user.css

_Any changes made were aimed to be non-destructive to older versions of Spotify so old classes will remain to work, new ones have simply been added to the lists where needed and a couple of fixes are applied specifically to new items._
This pull request aims to fix a various number of issues including the following:
- Fix Sidebar icons
- Fix Sidebar fade effect being incorrect color
- Fix user is able to scroll off the screen (scroll too far to the right into empty space)
- Fix Playback bar moving around when scrolling
- Fix Friends list
- Fix top gradient on the homepage that has come back after update

Number of Fixes

---

user.css

Changed to aria labels for podcast buttons to show missing podcast player buttons and removed gradient in the name in the player.

Add back podcast buttons and remove gradient in name

---

user.css

fixes issues with skipBack, skipForward, and the repeat button not appearing in the latest spicetify and spotify version.

updated user.css

---

bloom.js
color.ini
user.css

Hello! First thing I'd say is that I love the work you've done, it is a really amazing theme to use so keep up the good stuff <3
Just a few suggestions as to Marketplace compatibility that I've experienced while using the theme that could create some annoyances to the general user, would appreciate if you could take a look into it :)
Updated some class names to match recent CSS maps changes also
Resolves #29 
Resolves #33 
Resolves #36
Resolves #38 
<details>
<summary>Color problem screenshots</summary>
</details>
<details>
<summary>Screenshot showing changes are working as expected </summary>
</details>

chore: compatibility with Marketplace

---

user.css

removed the unnecessary changes from my old PR.

fix for issue #46

---

bloom.js
user.css

fix(tracklist): fix long playlist scrolling

---

user.css

fix: update class name

---

user.css

Just made a minor visual change to the Liked Songs button. Thought it looked nice alongside with the other playlist icons at the bottom. I think this is also how it originally was.

Minor visual change to "Liked Songs" button.

---

user.css

fixed it with one small change. (possibly fixes #65)

fix: Stretched playlist icons on playing/downloading state.

---

user.css

Just made improvements to the header title at the top of every playlist and artist pages.

Header title improvements

---

user.css

Fix album image gets blasted from existence on expand

fix: album image disappearing on expand

---

user.css

- added hover states to repeat and shuffle buttons
- changed active accent color of repeat and shuffle buttons to better match original Spotify look

enhancement: player controls (part II)

---

user.css

Fixed incorrect color when hovering over album cover (in search lists)

fix: tracklist album hover

---

user.css

Fixed even more alignment inconsistencies.

fix: more misalignments

---

user.css

Fixes incorrect color of liked songs icon from the artist profile.

fix: liked songs icon on artist profile

---

user.css

Fixed for latest version of Spotify.

[alignment fix] Update class names

---

user.css

two commits cause I accidentally omitted a line and misnamed the issue.

fix for issue #72

---

user.css

Took me a while to figure out, but here it is. (solves one of the issues in #13)

feat: Active/inactive state to buttons in Settings tab

---

README.md

Docs:(updating README.MD)

---

manifest.json

changing description and preview

docs:(updating manifest.json)

---

user.css

fix:(device banner width fix)

---

README.md

Docs:(update readme)

---

install.sh

See the mentioned issue for more info.
Test: Run the script before and after this commit. Before will try running all commands regardless. After will abort if Spicetify doesn't exist.

install(sh): Add preliminary check for Spicetify's existence (#119)

---

README.md
install_debian.sh

Also added a strong safeguard to abort if the distro isn't Debian or its derivative.

Initial script for Debian (#125)

---

bloom.js
user.css

i dont really know why you give so much right gap? is it for linux users?
```css 
/* fix window controls, hides profile*/
.main-userWidget-box {
bottom: 5px;
right: 150px;
}
```
~~and i make the avatar much bigger because i see it it was too small (it was my preference)~~
edit: i change my mind small avatar are much better xD
and vertically centering the back & forward button
and idk why you need 10sec of timeout i look up for dribble theme and they only need 100ms timeout so if u can tell why you need 10s of timeout please tell me
```js
function waitForElement(els, func, timeout = 10000) {...}
```
if it not fit on your preference please tell me

fix:play button cannot be interacted & some touch

---

install_debian.sh

* Just in case it's installed globally.

install_debian: Also modify global shortcut

---

user.css

i managed to fix this problem #99

fix:Spotify moving up caused by lyric page

---

user.css

i just realize that my avatar is oval XD so i fixed it

fix:avatar is oval

---

install_debian.sh

All of this is because of Pop_OS!...

install_debian: Harden ID check and add Pop_OS!

---

install_debian.sh

TODO: Merge install_debian with main install script.

install_debian: Cleanup and add Linux Mint

---

user.css

I found a solution to #138
The 8ce57bd43bc245deb96a11a3c20b641d9de08cfc is the problem.

connect to a device solution

---

bloom.js

fixes the playlist icons and gets them from spotify instead.  scroll now allows you to view all your playlist on the left side

fixes the playlist icons and scroll

---

README.md

Scheme Addition:(dark_mono)

---

user.css

Fixed fullscreen extension button alignments
#159

Fix:(Fullscreen button alignments)

---

user.css

make it more visible in dark themes and visible in light themes

Change color of timestamp in friends activity

---

bloom.js
user.css

- ### before: 
- ### after:
- ### before: 
- ### after:

Padding fixes

---

user.css

fix playlist description color

---

user.css

search bar padding improvements

---

user.css

add transparency to the top bar and search field

---

user.css

Settings page improvements

---

user.css

fix history buttons color

---

user.css

fix marketplace toggles

---

user.css

makes it colored in light theme

use accent color for tag container

---

user.css

finally a real fix, not a workaround

fix top elements padding

---

user.css

expand the background of lyrics

---

bloom.js
user.css

new categories card style

---

user.css

Reverts nimsandu/spicetify-bloom#179

Revert "use accent color for tag container"

---

user.css

Reverts nimsandu/spicetify-bloom#177

Revert "fix history buttons color"

---

install_debian.sh

* Ubuntu also suffers from this derp now.
* Fix the if-else statement.

install_debian: Some Quality of Life Enhancements

---

install.sh

Based on commit 5d55e51d6d4731da36c89b2b3b0b61c0d322a5b1 (add spotify installation check to the posh script).

install(sh): Check if Spotify is in PATH

---

user.css

restore default Lyrics Plus display style

---

user.css

align top bar items to center

---

user.css

dynamic height for add to playlist context submenu

---

user.css

add transperency to about artist and edit playlist pop-ups

---

user.css

expand default lyrics background

---

user.css

Change album art's vertical alignment to auto

---

user.css

fix clear search field button margin

---

user.css

add padding, fix alignment, change sizes

new lyrics style changes

---

user.css

just auto-formatted the file to avoid seeing a million warnings in the IDE

css style changes

---

user.css

fix stock player icons visibility in the built-in fs mode

---

user.css

player bar items padding fixes

---

bloom.js
user.css

dynamic lyrics backdrop brightness

---

theme.js
user.css

dynamic brightness (now for real) and saturation, new track change animation (now without artifacts), better overall performance (visibility hidden -> display none) and other minor changes

rewrite new lyrics style

---

src/user.css

unify friend activity padding for all languages

---

assets/phosphor-icons/infinity-bold.svg
assets/phosphor-icons/infinity.svg
src/user.css

add support for eternal jukebox

---

src/theme.js
src/user.css

initial LibraryX support

---

README.md

Addition:(libraryx style screenshots)

Update LibraryX screenshots

---

src/user.css

Fixes #309 where buttons in the topbar were unresponsive in the home page.

fix(user.css): make topbar buttons responsive & bring back topbar noise

---

src/user.css

Position of the Connect Bar was changed so that it doesn't interfere when the user wants to click something which was previously behind the bar.

fix(user.css): improve device picker & connectbar styles

---

src/user.css

Made the stats of eternal jukebox that were previously hidden behind the player bar, visible. 
Also made changes so that the header doesn't stick to the top.

fix(user.css): make eternal jukebox stats visible

---

src/theme.js
src/user.css

Made the "Create playlist or folder" button in Your Library header visible.

fix(theme.js): make create playlist button visible

---

src/user.css

fix(user.css): improve top bar buttons position in Linux & macOS

---

src/user.css

also changed button-size (main-playPauseButton-button) to 32px

fix(styles): update mask-image for cross-browser compatibility

---

src/user.css

Resolved an issue where list icons in libraryX were not visible due to incorrect CSS styling.
Issue: 
Expected Behavior:

fix(libraryX): correct CSS for list icons not showing

---

src/theme.js
src/user.css

Fixed Search bar unfocus issue https://github.com/nimsandu/spicetify-bloom/issues/332
Change some of the icons to inline 
Fixed Shuffle Button and Align Buttons (will find a way to add enhanced shuffle button as there is no icons from fluent for that)
Fixed Lyrics background
New full screen lyrics page
Add some blur and make it darker

Implement full-screen UI, fix lyrics background, update icons and masks

---

src/user.css

fix:(Buddy Feed & Player Slider)
